version: "3.4"

services:

  # Database
  bookstore-mysql-db:
    image: mysql:5.7
    container_name: bookstore-mysql-db
    hostname: bookstore-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'bookstore_db'
      MYSQL_USER: 'bookstoreDBA'
      MYSQL_PASSWORD: 'PaSSworD'
      MYSQL_ROOT_PASSWORD: 'r00tPaSSworD'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - bookstore-db-volume:/var/lib/mysql
    networks:
      - bookstore-app-network


  bookstore-monoservice:
    build:
      context: .
      args:
        JAR_FILE: bookstore-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: bookstore-monoservice
    container_name: bookstore-monoservice
    hostname: bookstore-monoservice
    ports:
      - "4001:4001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=4001
      - ZIPKIN_HOST=bookstore-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker

  # Tracing service
  bookstore-zipkin:
    image: openzipkin/zipkin
    container_name: bookstore-zipkin
    hostname: bookstore-zipkin
    ports:
      - "9411:9411"
    networks:
      - bookstore-app-network


volumes:
  bookstore-db-volume:


networks:
  bookstore-app-network:
    driver: bridge
